jobs:
  build:
    docker:
      - image: vsbogd/hyperon-ci:latest
    steps:
      - checkout
      - run:
          name: build C++
          command: |
            source activate hyperon
            mkdir build
            cd build
            cmake ..
            make
            make check
